title: Soumyajit Chakraborty - My Blog
author: GitHub User
email: soumyajit1729@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hello everybody,this is Soumyajit Chakraborty,a 2nd year undergraduate student of IIT Kharagpur and This is my own blog
  you can find specials events of my collegelife, my opinions about them.Actually I do not know clearly what 
  I am going to write here. So, stay stunned.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github:  soumyajit1729
    facebook: soumyajit.chakraborty.98837
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
